services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${HOMELAB_DATA_DIR}/jellyfin:/config
      - ${HOMELAB_DATA_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}/library:/media:ro
      - ${MEDIA_DIR}/downloads/complete:/downloads:ro
      - ./fonts:/fonts:ro
    expose:
      - "8096"
    networks:
      - proxy

  metatube:
    image: ghcr.io/metatube-community/metatube-server:1.4.0
    container_name: metatube
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ${HOMELAB_DATA_DIR}/jellyfin/plugin-servers/metatube:/data
    command: -dsn "/data/metatube.db" -port 8080 -db-auto-migrate -db-prepared-stmt
    networks:
      - proxy

networks:
  proxy:
    name: homelab_proxy
    external: true
