services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: homepage
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN}
      HOMEPAGE_VAR_DOMAIN: ${DOMAIN}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - "3000"
    networks:
      - proxy

networks:
  proxy:
    name: homelab_proxy
    external: true
